import type { MetadataRoute } from 'next';
import { SITE } from '@/lib/seo';

/**
 * robots.txt — generated by Next at /robots.txt.
 *
 * AI SEO: rather than block AI crawlers, we explicitly welcome them. This is a
 * free, public, privacy-respecting tool, so being cited by AI search engines
 * (ChatGPT, Claude, Perplexity, Gemini, etc.) is purely upside. No private or
 * secret data is ever served — passwords never leave the browser — so there is
 * nothing to protect from indexing.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
      },
    ],
    sitemap: `${SITE.url}/sitemap.xml`,
    host: SITE.url,
  };
}
